### ISSUE TITLE
API: return all candidates for an office

### ISSUE THREAD

**Issue by mapsandapps** [jordanstreiff/atlanta-candidate-api#15]
This already exists for district councilmembers, but I don't see it for mayor, council president, and the at-large posts. This would be similar to `/api/districts/4` but for those offices.

**Comment by greghaygood** [comment]
There seems to have been an endpoint for /offices previously, but it was removed. Any reason why @jordanstreiff ?

**Comment by rmody3** [comment]
The pull request i just opened added an /offices/:id or /offices/:slug endpoint, i just joined this project yesterday, so let me know if this works with the way everyone is thinking or not.

**Comment by jordanstreiff** [comment]
@rmody3 well done - this is merged. Going to close this out.
