### ISSUE TITLE
Possible improvement to /candidates endpoint

### ISSUE THREAD

**Issue by mapsandapps** [jordanstreiff/atlanta-candidate-api#16]
I don't think having 'office' for each of these is necessary. It feels a bit redundant to do `data.offices[0].office.candidates` for example. I'm not sure if more data is planned for here, but if not, I propose removing that extra layer in the object, so

```
  "offices": [
    {
      "office": {
        "name": "Mayor",
        "candidates": [
          {
            "id": 1,
            "first_name": "Vincent",
            "last_name": "Fort"
          },
          ...
        ]
      }
    }
  ]
```

would become
```
  "offices": [
    {
      "name": "Mayor",
      "candidates": [
        {
          "id": 1,
          "first_name": "Vincent",
          "last_name": "Fort"
        },
        ...
      ]
    }
  ]
```

**Comment by tb9jordan** [comment]
I agree @mapsandapps. Will tackle this when I get a chance unless someone else gets to it first.

**Comment by jordanstreiff** [comment]
Resolved
