### ISSUE TITLE
Resolve CORS issue

### ISSUE THREAD

**Issue by mapsandapps** [jordanstreiff/atlanta-candidate-api#18]
```XMLHttpRequest cannot load https://atlanta-candidate-api.herokuapp.com/api/candidates. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://codeforatlanta.github.io' is therefore not allowed access.```

For now, the front-end will be hosted at `https://codeforatlanta.github.io/atlanta-candidate-ui/`, so please provide that URL access.

**Comment by Th3R3p0** [comment]
I will take this one

**Comment by Th3R3p0** [comment]
@jordanstreiff I think the issue is still occurring. You may want to change the regex to be `/https:\/\/codeforatlanta\.github\.io/`. It appears the browser is requesting it for https://codeforatlanta.github.io and not https://codeforatlanta.github.io/atlanta-candidate-ui/.

**Comment by jordanstreiff** [comment]
@Th3R3p0 you are correct. made the update and it works now. we should also create an issue to update cors so that anyone can use - this is intended to be an open api.

**Comment by Th3R3p0** [comment]
@jordanstreiff you can allow any site to make a request by doing `'*'` instead of the regex. This has security implications, but it would be required for other web applications to display data in a browser requested from the API.
