### ISSUE TITLE
Dangling Issue/Media code

### ISSUE THREAD

**Issue by greghaygood** [jordanstreiff/atlanta-candidate-api#19]
It seems that there was originally models & such for Issues and Media, but those were refactored out a few commits back. There's still a lot of related code that no longer works, such as relationships in the Candidate model, tests that no longer make sense, etc.

Should these leftovers also be removed, or is there a plan to refactor those elsewhere into the code?

**Comment by tb9jordan** [comment]
Good catch @greghaygood. Let's remove it. Feel free to continue the work you started in your pull request - I'll wait to merge. Unless you want to separate it.

**Comment by greghaygood** [comment]
Sounds good - I'll clean that up now and send another PR.
