### ISSUE TITLE
Modify districts endpoint

### ISSUE THREAD

**Issue by loisaidasam** [jordanstreiff/atlanta-candidate-api#22]
I propose that the `/districts` endpoint be moved to another `/candidates` endpoint.

From a restful resource "thing" perspective, the "things" we're returning are candidates, not districts.

Specifically:

`api/districts/:id` -> `api/candidates/?district=:id`

Thoughts?

**Comment by mapsandapps** [comment]
I like this idea. Then the `districts` endpoint could return all candidates for a voter in that district, a la #14

**Comment by loisaidasam** [comment]
@mapsandapps cool idea, but wouldn't that make more sense to be something like `/api/elections/?district=:id` or `/api/offices/?district=:id` since the "things" we're talking about at that point are elections/offices?

**Comment by mapsandapps** [comment]
Sure, `/api/offices/?district=:id` sounds good to me. I've been calling them "offices" on the front end.

**Comment by mapsandapps** [comment]
I guess the question is whether I would expect `/api/offices/?district=:id` to return just the city council district or whether I would expect it to return all the offices for a voter in that district, like listed in #14. Maybe we need another query parameter?

**Comment by loisaidasam** [comment]
Another idea would be to create endpoints such as:

- `/api/district/:id/candidates`
- `/api/district/:id/offices`
- `/api/district/:id/elections`

from which you can infer that the "things" (candidates, offices, elections) belong to the given district.

**Comment by jordanstreiff** [comment]
We need to be able to return three different sets of candidates... all candidates, citywide candidates, and single district candidates. I agree with the initial comment that candidates endpoint is the best place for this. I think an additional param could accomplish this with the least restructuring.

**Comment by jordanstreiff** [comment]
Then we can have Offices return just the office info... name, district id, etc. Maybe you could also specify whether you candidates along with your basic office info? Of course then it would essentially be duplicating the candidates endpoint, because candidates are organized by office.

**Comment by jordanstreiff** [comment]
Made some modifications and pulled into master - any objects pls make a new issue.
