### ISSUE TITLE
what does simple front end build out look like

### ISSUE THREAD

**Issue by bbrewington** [jordanstreiff/atlanta-candidate-api#4]

**Comment by mapsandapps** [comment]
I took a first pass at wireframes. https://marvelapp.com/hdicg9g

**Comment by jordanstreiff** [comment]
Looks good @mapsandapps ! Like the direction. Two thoughts - 

1. What does error handling (no address found) look like?
2. Hoping to add board of education support at some point - what would a design that was flexible enough to support BoE look like?

**Comment by jordanstreiff** [comment]
let's move discussion of front end issues over to the front end repo.
